URL in Maven deploy is an optional field
Passing a blank URL will cause the build to fail with
ERROR: Failed to deploy artifacts/metadata: Cannot access with type
default using the available connector factories:
WagonRepositoryConnectorFactory

Change-Id: Iab142155542f69e8ff876e7b24fd4e460b670ae8
Signed-off-by: Thanh Ha <thanh.ha@linuxfoundation.org>