Constrain PyYAML to v3.x.
PyYAML v4.1 was released which breaks the `!!python/tuple` syntax with the
following error:

yaml.constructor.ConstructorError: could not determine a constructor for the tag
'tag:yaml.org,2002:python/tuple'

Change-Id: Iaf838b111e6dfad5dc5c1f904a482b525e99a911